@echo off
echo Adding changes...
git add .
echo Committing changes...
git commit -m "feat: migrate authentication to email OTP"
echo Pushing to GitHub...
git push origin main
echo Done! Please close this window.
pause
