@echo off
echo Adding changes...
git add .
echo Committing changes...
git commit -m "fix: resolve schema merge conflicts, restore missing Dashboard imports, and fix Java backend warnings"
echo Pushing to GitHub...
git push origin main
echo Done! Please close this window.
pause
