services:
  postgres:
    image: postgres:15
    container_name: monument-postgres
    environment:
      POSTGRES_DB: monumentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Siri@2007
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monument-network

  spring-boot:
    build:
      context: ./backend-spring
      dockerfile: Dockerfile
    container_name: monument-spring-boot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monumentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Siri@2007
    networks:
      - monument-network

volumes:
  postgres_data:

networks:
  monument-network:
    driver: bridge